site_name: Transport for Athens
docs_dir: '../../docs/el'
site_dir: '../../public/el'
site_url: https://transportforathens.gitlab.io/el/
nav:
  - Αρχική: index.md
theme:
  name: material
  custom_dir: '../../overrides/'
  language: el
  logo: assets/images/TransportForAthens_logo_navbar.png
  favicon: assets/images/TransportForAthens_logo_favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
extra:
  alternate:
    - name: Ελληνικά
      link: /el/
      lang: el
    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/transportforathens.org
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dimnioras/
    - icon: fontawesome/solid/globe
      link: https://dimnioras.com/
  copyright: Copyright